name: ci future

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x

      - name: Check types
        env:
          DENO_FUTURE: 1
        run: deno task check:types

      - name: Verify formatting
        env:
          DENO_FUTURE: 1
        run: deno fmt --check

      - name: Run linter
        env:
          DENO_FUTURE: 1
        run: deno lint

      - name: Run tests
        env:
          DENO_FUTURE: 1
        run: deno task test
